modLoader="javafml" #mandatory
loaderVersion="${fml_version_spec}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="bundledelight" #mandatory
version="${version}" #mandatory
displayName="Bundled Delight" #mandatory
logoFile="logo.png" #optional
credits="PouffyDev & All the authors of the Mods this utilizes." #optional
authors="${author}" #optional
description='''
Bundled Delight is a mod that aims to add features connecting Farmer's Delight Add-Ons such as Brewin' & Chewin', Farmer's Respite and Miner's Delight!
'''
[[dependencies.bundledelight]] #optional
    modId="forge"
    mandatory=true
    versionRange="${forge_version_spec}"
    ordering="NONE"
    side="BOTH"
[[dependencies.bundledelight]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_spec}"
    ordering="NONE"
    side="BOTH"
[[dependencies.bundledelight]]
    modId="farmersdelight"
    mandatory=true
    versionRange="${farmers_delight_version_spec}"
    ordering="NONE"
    side="BOTH"
[[dependencies.bundledelight]]
    modId="brewinandchewin"
    mandatory=false
    versionRange="${brewinandchewin_version_spec}"
    ordering="BEFORE"
    side="BOTH"