modLoader="javafml"

loaderVersion="${loader_version_range}"

license="${mod_license}"

issueTrackerURL="https://github.com/pouffy/Bundled-Delights/issues"

[[mods]]

modId="${mod_id}"

version="${mod_version}"

displayName="${mod_name}"

#updateJSONURL="https://change.me.example.invalid/updates.json"

displayURL="https://github.com/pouffy/Bundled-Delights"

logoFile="bundled_delight.png"

credits="PouffyDev & All the authors of the Mods this utilizes."

authors="${mod_authors}"

description='''${mod_description}'''

[[mixins]]
config="${mod_id}.mixins.json"

#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"


[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
